name: Generate Sitemap

on:
  push:
    branches:
      - github-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run sitemap generation script
      run: node sitemap.js

    - name: Commit and push sitemap
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add sitemap.xml
        git commit -m 'Generate sitemap'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}